spring:
   cloud:
      gateway:
         globalcors:
            corsConfigurations:
               '[/**]':
                  allowedOrigins: '*'
                  allowedHeaders: '*'
                  allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
         routes:
         -  id: DataInputService
            uri: lb://DATAINPUTSERVICE
            predicates:
            - Path=/dis/**